import "./globals.css"
import clsx from "clsx"
import NavigationBar from "@/components/NavigationBar"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>
          {children}
          <NavigationBar />
        </div>
      </body>
    </html>
  )
}
